services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamnet

  springboot-app:
    image: maven:3.9.6-eclipse-temurin-21
    ports:
      - "8082:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      PYTHON_BASE_URL: http://python:8000
    volumes:
      - .:/app
    working_dir: /app
    command: mvn spring-boot:run
    depends_on:
      - postgres-db
    networks:
      - streamnet

volumes:
  postgres_data:
networks:
  streamnet:
    driver: bridge
